/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";

// Create Virtual Routes

const SessionsLazyImport = createFileRoute("/sessions")();

// Create/Update Routes

const SessionsLazyRoute = SessionsLazyImport.update({
  id: "/sessions",
  path: "/sessions",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/sessions.lazy").then((d) => d.Route));

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/sessions": {
      id: "/sessions";
      path: "/sessions";
      fullPath: "/sessions";
      preLoaderRoute: typeof SessionsLazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/sessions": typeof SessionsLazyRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/sessions": typeof SessionsLazyRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/sessions": typeof SessionsLazyRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/sessions";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/sessions";
  id: "__root__" | "/" | "/sessions";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SessionsLazyRoute: typeof SessionsLazyRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessionsLazyRoute: SessionsLazyRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/sessions"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/sessions": {
      "filePath": "sessions.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
