/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";

// Create Virtual Routes

const SectionsLazyImport = createFileRoute("/sections")();
const MenusLazyImport = createFileRoute("/menus")();
const HomeLazyImport = createFileRoute("/home")();
const DrinksLazyImport = createFileRoute("/drinks")();
const DishesLazyImport = createFileRoute("/dishes")();

// Create/Update Routes

const SectionsLazyRoute = SectionsLazyImport.update({
  id: "/sections",
  path: "/sections",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/sections.lazy").then((d) => d.Route));

const MenusLazyRoute = MenusLazyImport.update({
  id: "/menus",
  path: "/menus",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/menus.lazy").then((d) => d.Route));

const HomeLazyRoute = HomeLazyImport.update({
  id: "/home",
  path: "/home",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/home.lazy").then((d) => d.Route));

const DrinksLazyRoute = DrinksLazyImport.update({
  id: "/drinks",
  path: "/drinks",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/drinks.lazy").then((d) => d.Route));

const DishesLazyRoute = DishesLazyImport.update({
  id: "/dishes",
  path: "/dishes",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/dishes.lazy").then((d) => d.Route));

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/dishes": {
      id: "/dishes";
      path: "/dishes";
      fullPath: "/dishes";
      preLoaderRoute: typeof DishesLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/drinks": {
      id: "/drinks";
      path: "/drinks";
      fullPath: "/drinks";
      preLoaderRoute: typeof DrinksLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/home": {
      id: "/home";
      path: "/home";
      fullPath: "/home";
      preLoaderRoute: typeof HomeLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/menus": {
      id: "/menus";
      path: "/menus";
      fullPath: "/menus";
      preLoaderRoute: typeof MenusLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/sections": {
      id: "/sections";
      path: "/sections";
      fullPath: "/sections";
      preLoaderRoute: typeof SectionsLazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dishes": typeof DishesLazyRoute;
  "/drinks": typeof DrinksLazyRoute;
  "/home": typeof HomeLazyRoute;
  "/menus": typeof MenusLazyRoute;
  "/sections": typeof SectionsLazyRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/dishes": typeof DishesLazyRoute;
  "/drinks": typeof DrinksLazyRoute;
  "/home": typeof HomeLazyRoute;
  "/menus": typeof MenusLazyRoute;
  "/sections": typeof SectionsLazyRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/dishes": typeof DishesLazyRoute;
  "/drinks": typeof DrinksLazyRoute;
  "/home": typeof HomeLazyRoute;
  "/menus": typeof MenusLazyRoute;
  "/sections": typeof SectionsLazyRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/dishes" | "/drinks" | "/home" | "/menus" | "/sections";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/dishes" | "/drinks" | "/home" | "/menus" | "/sections";
  id:
    | "__root__"
    | "/"
    | "/dishes"
    | "/drinks"
    | "/home"
    | "/menus"
    | "/sections";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DishesLazyRoute: typeof DishesLazyRoute;
  DrinksLazyRoute: typeof DrinksLazyRoute;
  HomeLazyRoute: typeof HomeLazyRoute;
  MenusLazyRoute: typeof MenusLazyRoute;
  SectionsLazyRoute: typeof SectionsLazyRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DishesLazyRoute: DishesLazyRoute,
  DrinksLazyRoute: DrinksLazyRoute,
  HomeLazyRoute: HomeLazyRoute,
  MenusLazyRoute: MenusLazyRoute,
  SectionsLazyRoute: SectionsLazyRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dishes",
        "/drinks",
        "/home",
        "/menus",
        "/sections"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dishes": {
      "filePath": "dishes.lazy.tsx"
    },
    "/drinks": {
      "filePath": "drinks.lazy.tsx"
    },
    "/home": {
      "filePath": "home.lazy.tsx"
    },
    "/menus": {
      "filePath": "menus.lazy.tsx"
    },
    "/sections": {
      "filePath": "sections.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
