/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpaceRouteImport } from './routes/space'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as LineHeightRouteImport } from './routes/line-height'
import { Route as FontWeightRouteImport } from './routes/font-weight'
import { Route as FontFamilyRouteImport } from './routes/font-family'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ColorRouteImport } from './routes/color'
import { Route as IndexRouteImport } from './routes/index'
import { Route as receiptsReceiptsRouteImport } from './routes/(receipts)/receipts'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const SpaceRoute = SpaceRouteImport.update({
  id: '/space',
  path: '/space',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const LineHeightRoute = LineHeightRouteImport.update({
  id: '/line-height',
  path: '/line-height',
  getParentRoute: () => rootRouteImport,
} as any)
const FontWeightRoute = FontWeightRouteImport.update({
  id: '/font-weight',
  path: '/font-weight',
  getParentRoute: () => rootRouteImport,
} as any)
const FontFamilyRoute = FontFamilyRouteImport.update({
  id: '/font-family',
  path: '/font-family',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorRoute = ColorRouteImport.update({
  id: '/color',
  path: '/color',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const receiptsReceiptsRoute = receiptsReceiptsRouteImport.update({
  id: '/(receipts)/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/color': typeof ColorRoute
  '/demo': typeof DemoRoute
  '/font-family': typeof FontFamilyRoute
  '/font-weight': typeof FontWeightRoute
  '/line-height': typeof LineHeightRoute
  '/playground': typeof PlaygroundRoute
  '/space': typeof SpaceRoute
  '/receipts': typeof receiptsReceiptsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/color': typeof ColorRoute
  '/demo': typeof DemoRoute
  '/font-family': typeof FontFamilyRoute
  '/font-weight': typeof FontWeightRoute
  '/line-height': typeof LineHeightRoute
  '/playground': typeof PlaygroundRoute
  '/space': typeof SpaceRoute
  '/receipts': typeof receiptsReceiptsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/color': typeof ColorRoute
  '/demo': typeof DemoRoute
  '/font-family': typeof FontFamilyRoute
  '/font-weight': typeof FontWeightRoute
  '/line-height': typeof LineHeightRoute
  '/playground': typeof PlaygroundRoute
  '/space': typeof SpaceRoute
  '/(receipts)/receipts': typeof receiptsReceiptsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/color'
    | '/demo'
    | '/font-family'
    | '/font-weight'
    | '/line-height'
    | '/playground'
    | '/space'
    | '/receipts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/color'
    | '/demo'
    | '/font-family'
    | '/font-weight'
    | '/line-height'
    | '/playground'
    | '/space'
    | '/receipts'
  id:
    | '__root__'
    | '/'
    | '/color'
    | '/demo'
    | '/font-family'
    | '/font-weight'
    | '/line-height'
    | '/playground'
    | '/space'
    | '/(receipts)/receipts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColorRoute: typeof ColorRoute
  DemoRoute: typeof DemoRoute
  FontFamilyRoute: typeof FontFamilyRoute
  FontWeightRoute: typeof FontWeightRoute
  LineHeightRoute: typeof LineHeightRoute
  PlaygroundRoute: typeof PlaygroundRoute
  SpaceRoute: typeof SpaceRoute
  receiptsReceiptsRoute: typeof receiptsReceiptsRoute
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$'
  id: '__root__' | '/api/auth/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/space': {
      id: '/space'
      path: '/space'
      fullPath: '/space'
      preLoaderRoute: typeof SpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/line-height': {
      id: '/line-height'
      path: '/line-height'
      fullPath: '/line-height'
      preLoaderRoute: typeof LineHeightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/font-weight': {
      id: '/font-weight'
      path: '/font-weight'
      fullPath: '/font-weight'
      preLoaderRoute: typeof FontWeightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/font-family': {
      id: '/font-family'
      path: '/font-family'
      fullPath: '/font-family'
      preLoaderRoute: typeof FontFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color': {
      id: '/color'
      path: '/color'
      fullPath: '/color'
      preLoaderRoute: typeof ColorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(receipts)/receipts': {
      id: '/(receipts)/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof receiptsReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColorRoute: ColorRoute,
  DemoRoute: DemoRoute,
  FontFamilyRoute: FontFamilyRoute,
  FontWeightRoute: FontWeightRoute,
  LineHeightRoute: LineHeightRoute,
  PlaygroundRoute: PlaygroundRoute,
  SpaceRoute: SpaceRoute,
  receiptsReceiptsRoute: receiptsReceiptsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
