/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LifeosRouteImport } from './routes/lifeos'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as LifeosIndexRouteImport } from './routes/lifeos.index'
import { Route as LifeosReceiptsRouteImport } from './routes/lifeos.receipts'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeosRoute = LifeosRouteImport.update({
  id: '/lifeos',
  path: '/lifeos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeosIndexRoute = LifeosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LifeosRoute,
} as any)
const LifeosReceiptsRoute = LifeosReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => LifeosRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/demo': typeof DemoRoute
  '/lifeos': typeof LifeosRouteWithChildren
  '/login': typeof LoginRoute
  '/lifeos/receipts': typeof LifeosReceiptsRoute
  '/lifeos/': typeof LifeosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/lifeos/receipts': typeof LifeosReceiptsRoute
  '/lifeos': typeof LifeosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/demo': typeof DemoRoute
  '/lifeos': typeof LifeosRouteWithChildren
  '/login': typeof LoginRoute
  '/lifeos/receipts': typeof LifeosReceiptsRoute
  '/lifeos/': typeof LifeosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/demo'
    | '/lifeos'
    | '/login'
    | '/lifeos/receipts'
    | '/lifeos/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/demo' | '/login' | '/lifeos/receipts' | '/lifeos' | '/api/auth/$'
  id:
    | '__root__'
    | '/demo'
    | '/lifeos'
    | '/login'
    | '/lifeos/receipts'
    | '/lifeos/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DemoRoute: typeof DemoRoute
  LifeosRoute: typeof LifeosRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifeos': {
      id: '/lifeos'
      path: '/lifeos'
      fullPath: '/lifeos'
      preLoaderRoute: typeof LifeosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifeos/': {
      id: '/lifeos/'
      path: '/'
      fullPath: '/lifeos/'
      preLoaderRoute: typeof LifeosIndexRouteImport
      parentRoute: typeof LifeosRoute
    }
    '/lifeos/receipts': {
      id: '/lifeos/receipts'
      path: '/receipts'
      fullPath: '/lifeos/receipts'
      preLoaderRoute: typeof LifeosReceiptsRouteImport
      parentRoute: typeof LifeosRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LifeosRouteChildren {
  LifeosReceiptsRoute: typeof LifeosReceiptsRoute
  LifeosIndexRoute: typeof LifeosIndexRoute
}

const LifeosRouteChildren: LifeosRouteChildren = {
  LifeosReceiptsRoute: LifeosReceiptsRoute,
  LifeosIndexRoute: LifeosIndexRoute,
}

const LifeosRouteWithChildren =
  LifeosRoute._addFileChildren(LifeosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DemoRoute: DemoRoute,
  LifeosRoute: LifeosRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
