/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpaceRouteImport } from './routes/space'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as LineHeightRouteImport } from './routes/line-height'
import { Route as FontWeightRouteImport } from './routes/font-weight'
import { Route as FontFamilyRouteImport } from './routes/font-family'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ColorRouteImport } from './routes/color'
import { Route as IndexRouteImport } from './routes/index'

const SpaceRoute = SpaceRouteImport.update({
  id: '/space',
  path: '/space',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const LineHeightRoute = LineHeightRouteImport.update({
  id: '/line-height',
  path: '/line-height',
  getParentRoute: () => rootRouteImport,
} as any)
const FontWeightRoute = FontWeightRouteImport.update({
  id: '/font-weight',
  path: '/font-weight',
  getParentRoute: () => rootRouteImport,
} as any)
const FontFamilyRoute = FontFamilyRouteImport.update({
  id: '/font-family',
  path: '/font-family',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorRoute = ColorRouteImport.update({
  id: '/color',
  path: '/color',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/color': typeof ColorRoute
  '/demo': typeof DemoRoute
  '/font-family': typeof FontFamilyRoute
  '/font-weight': typeof FontWeightRoute
  '/line-height': typeof LineHeightRoute
  '/playground': typeof PlaygroundRoute
  '/space': typeof SpaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/color': typeof ColorRoute
  '/demo': typeof DemoRoute
  '/font-family': typeof FontFamilyRoute
  '/font-weight': typeof FontWeightRoute
  '/line-height': typeof LineHeightRoute
  '/playground': typeof PlaygroundRoute
  '/space': typeof SpaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/color': typeof ColorRoute
  '/demo': typeof DemoRoute
  '/font-family': typeof FontFamilyRoute
  '/font-weight': typeof FontWeightRoute
  '/line-height': typeof LineHeightRoute
  '/playground': typeof PlaygroundRoute
  '/space': typeof SpaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/color'
    | '/demo'
    | '/font-family'
    | '/font-weight'
    | '/line-height'
    | '/playground'
    | '/space'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/color'
    | '/demo'
    | '/font-family'
    | '/font-weight'
    | '/line-height'
    | '/playground'
    | '/space'
  id:
    | '__root__'
    | '/'
    | '/color'
    | '/demo'
    | '/font-family'
    | '/font-weight'
    | '/line-height'
    | '/playground'
    | '/space'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColorRoute: typeof ColorRoute
  DemoRoute: typeof DemoRoute
  FontFamilyRoute: typeof FontFamilyRoute
  FontWeightRoute: typeof FontWeightRoute
  LineHeightRoute: typeof LineHeightRoute
  PlaygroundRoute: typeof PlaygroundRoute
  SpaceRoute: typeof SpaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/space': {
      id: '/space'
      path: '/space'
      fullPath: '/space'
      preLoaderRoute: typeof SpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/line-height': {
      id: '/line-height'
      path: '/line-height'
      fullPath: '/line-height'
      preLoaderRoute: typeof LineHeightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/font-weight': {
      id: '/font-weight'
      path: '/font-weight'
      fullPath: '/font-weight'
      preLoaderRoute: typeof FontWeightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/font-family': {
      id: '/font-family'
      path: '/font-family'
      fullPath: '/font-family'
      preLoaderRoute: typeof FontFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color': {
      id: '/color'
      path: '/color'
      fullPath: '/color'
      preLoaderRoute: typeof ColorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColorRoute: ColorRoute,
  DemoRoute: DemoRoute,
  FontFamilyRoute: FontFamilyRoute,
  FontWeightRoute: FontWeightRoute,
  LineHeightRoute: LineHeightRoute,
  PlaygroundRoute: PlaygroundRoute,
  SpaceRoute: SpaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
