name: deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::085520092983:role/Github
          role-duration-seconds: 14390
          aws-region: us-east-1

      - name: cache turbo build
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-build-

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 22.5.0
          cache: "pnpm"

      - name: install dependencies
        run: pnpm install

      - name: build
        run: pnpm build

      - name: deploy
        run: pnpm deploy:production
