name: publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WINNIE_UI_GITHUB_TOKEN }}
          fetch-depth: 0

      - name: cache turbo build
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-build-

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.7.0
          run_install: false

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 22.5.0
          cache: "pnpm"

      - name: install dependencies
        run: pnpm install

      - name: create release pull request or publish to npm
        uses: changesets/action@v1
        with:
          publish: pnpm changeset:publish
        env:
          GITHUB_TOKEN: ${{ secrets.WINNIE_UI_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.WINNIE_UI_NPM_TOKEN }}
